/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as StaffAccessCrgRouteImport } from './routes/staff-access-crg'
import { Route as AuthenticatedCrgAdminRouteImport } from './routes/_authenticated/crg-admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAccessCrgRoute = StaffAccessCrgRouteImport.update({
  id: '/staff-access-crg',
  path: '/staff-access-crg',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrgAdminRoute = AuthenticatedCrgAdminRouteImport.update({
  id: '/crg-admin',
  path: '/crg-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/staff-access-crg': typeof StaffAccessCrgRoute
  '/crg-admin': typeof AuthenticatedCrgAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/staff-access-crg': typeof StaffAccessCrgRoute
  '/crg-admin': typeof AuthenticatedCrgAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/staff-access-crg': typeof StaffAccessCrgRoute
  '/_authenticated/crg-admin': typeof AuthenticatedCrgAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects' | '/staff-access-crg' | '/crg-admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects' | '/staff-access-crg' | '/crg-admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/projects'
    | '/staff-access-crg'
    | '/_authenticated/crg-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  StaffAccessCrgRoute: typeof StaffAccessCrgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-access-crg': {
      id: '/staff-access-crg'
      path: '/staff-access-crg'
      fullPath: '/staff-access-crg'
      preLoaderRoute: typeof StaffAccessCrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crg-admin': {
      id: '/_authenticated/crg-admin'
      path: '/crg-admin'
      fullPath: '/crg-admin'
      preLoaderRoute: typeof AuthenticatedCrgAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCrgAdminRoute: typeof AuthenticatedCrgAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCrgAdminRoute: AuthenticatedCrgAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  StaffAccessCrgRoute: StaffAccessCrgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
